name: get_video_thumbnail
description: A flutter plugin for creating a thumbnail from a local video file or from a video URL.
version: 0.7.0
repository: https://github.com/Kasun-thilina/video_thumbnail
homepage: https://github.com/Kasun-thilina/video_thumbnail

environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.3+4
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: get_video_thumbnail
    platforms:
      android:
        package: dev.kasunthilina.get_video_thumbnail
        pluginClass: GetVideoThumbnailPlugin
      ios:
        pluginClass: GetVideoThumbnailPlugin
      web:
        pluginClass: VideoThumbnailWeb
        fileName: video_thumbnail_web.dart
